### ISSUE TITLE
Method \'one.image.lock\' not defined

### ISSUE THREAD

**Issue by petrmalkov** [OpenNebula/addon-image-backup#4]
./one-image-backup.js -dvD

#============================================================
Lock image ID: 2
{ Error: XML-RPC fault: Method 'one.image.lock' not defined
    at createFault (/root/one-image-backup/node_modules/xmlrpc/lib/deserializer.js:82:21)
    at Deserializer.onDone (/root/one-image-backup/node_modules/xmlrpc/lib/deserializer.js:88:21)
    at SAXStream.emit (events.js:189:13)
    at SAXParser.SAXStream._parser.onend (/root/one-image-backup/node_modules/xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/root/one-image-backup/node_modules/xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/root/one-image-backup/node_modules/xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at SAXParser.end (/root/one-image-backup/node_modules/xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/root/one-image-backup/node_modules/xmlrpc/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (_stream_readable.js:629:10)
    at Object.onceWrapper (events.js:277:13)
  code: -506,
  faultCode: -506,
  faultString: 'Method \'one.image.lock\' not defined' }

added:
one.version(function(err, data) {
  console.log(data);
  process.exit(0);
  });

./one-image-backup.js -dvD
5.4.13

TM_MAD == qcow2

**Comment by feldsam** [comment]
Hello, sorry, I have to update docs, opennebula 5.6+ is required. Probably we can add some configuration option for enabling/disabling lock functionality.

**Comment by petrmalkov** [comment]
yes please
we need this version

**Comment by feldsam** [comment]
Just release version 1.10.0 with new config option `lockResources`. After upate run `npm install` to fetch latest dependencies.
